In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter
from math import ceil
import swifter
import random
pd.set_option('display.max_columns', None)

out_folder = './'

In [4]:
df = pd.read_csv("/home/eligol/Documents/01_WIS/01_Rarevar/outputs/statistics_output/PP_htseq_gene/raw_stat_mutated_processed.tsv", sep = '\t')
df_unmutated = pd.read_csv("/home/eligol/Documents/01_WIS/01_Rarevar/outputs/statistics_output/PP_htseq_gene/raw_stat_unmutated_processed.tsv", sep = '\t')
df_filtered = pd.read_csv("/home/eligol/Documents/01_WIS/01_Rarevar/outputs/statistics_output/PP_htseq_gene/raw_stat_mutated_filtered_processed.tsv", sep = '\t')
df_filtered_unmutated = pd.read_csv("/home/eligol/Documents/01_WIS/01_Rarevar/outputs/statistics_output/PP_htseq_gene/raw_stat_unmutated_filtered_processed.tsv", sep = '\t')

# df = pd.read_csv("/home/eligol/Documents/01_WIS/01_Rarevar/data/raw_Stats_files/human_RSS9451/raw_stats.tsv", sep = '\t')
# df_unmutated = pd.read_csv("/home/eligol/Documents/01_WIS/01_Rarevar/data/raw_Stats_files/human_RSS9451/raw_unmutated_stats.tsv", sep = '\t')

# df['position'] = df.Chromosome.str.cat(df['start'].astype(str), sep = ':')
# df['position'] = df.position.str.cat(df['end'].astype(str), sep = '-')
# df['position'] = df.position.str.cat(df['strand'].astype(str), sep = ',')
# df.rename(columns = {'cell barcodes':'count of mutated cell barcodes','R->A multi': 'R->A multi reads', 
#                      'R->T multi': 'R->T multi reads', 'R->G multi': 'R->G multi reads','R->C multi': 'R->C multi reads',
#                     'R->A single': 'R->A single read', 'R->T single': 'R->T single read','R->G single': 'R->G single read',
#                      'R->C single': 'R->C single read'}, inplace = True)
# df.sort_values(by = 'position', ascending=True, inplace = True, ignore_index = True)

# # add columns for total umi counts
# mutation_cols = df.columns[df.columns.str.startswith(('R->'))]
# df['total umi count'] = df[mutation_cols].sum(axis = 1)

# #create filtered df
# filtered_idx = df.groupby('position')['cell barcode'].filter( # ,'total umi count'
#     lambda x: (x.nunique() >= 5)) #& (x['total umi count'].sum() > 1)
# df_filtered = df.loc[filtered_idx.index,:]
df

,Chromosome,start,end,cell barcode,percent of non ref,strand,reference base,R->A multi reads,R->C multi reads,R->G multi reads,R->T multi reads,R->A single reads,R->C single reads,R->G single reads,R->T single reads,mixed reads,position,total umi count
0,chr11,61807541,61807542,TTCTCAAAGCGTAATA-1,100,-,a,0,1,0,0,0,0,0,0,0,"chr11:61807541-61807542,-",1
1,chr11,61867597,61867598,TTCTCAAAGCGTAATA-1,100,-,a,0,0,0,1,0,0,0,0,0,"chr11:61867597-61867598,-",1
2,chr11,62317797,62317798,TTCTCAAAGCGTAATA-1,100,-,t,0,0,1,0,0,0,0,0,0,"chr11:62317797-62317798,-",1
3,chr11,62604752,62604753,GTACTCCTCTCTAGGA-1,33,+,t,0,0,0,2,0,1,0,0,0,"chr11:62604752-62604753,+",3
4,chr11,67458397,67458398,ACGCAGCCACTTGGAT-1,100,+,g,0,0,0,0,1,0,0,0,0,"chr11:67458397-67458398,+",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612240,chr14,93634214,93634215,TTTCCTCCATGCTGGC-1,100,-,g,1,0,0,0,0,0,0,0,0,"chr14:93634214-93634215,-",1
612241,chr14,93634220,93634221,TTTCCTCCATGCTGGC-1,100,-,g,1,0,0,0,0,0,0,0,0,"chr14:93634220-93634221,-",1
612242,chr14,93531957,93531958,CGCCAAGCATCTCCCA-1,100,-,c,1,0,0,0,0,0,0,0,0,"chr14:93531957-93531958,-",1
612243,chr14,93634156,93634157,ATTTCTGAGTCACGCC-1,100,-,g,1,0,0,0,0,0,0,0,0,"chr14:93634156-93634157,-",1
612244,chr14,93634162,93634163,ATTTCTGAGTCACGCC-1,100,-,g,1,0,0,0,0,0,0,0,0,"chr14:93634162-93634163,-",1

In [ ]:
filtered_idx = df.groupby('position')[col].filter(lambda x: x.nunique() >= min_to_filter)
df.loc[filtered_idx.index, :]

In [5]:
df_unmutated = pd.read_csv("/home/eligol/Documents/01_WIS/01_Rarevar/data/raw_Stats_files/removed/ADAR/concatenated_tsv/raw_stats_unmutated_removed_ADAR.tsv", sep = '\t')
df_unmutated['position'] = df_unmutated.chromosome.str.cat(df_unmutated['start'].astype(str), sep = ':')
df_unmutated['position'] = df_unmutated.position.str.cat(df_unmutated['end'].astype(str), sep = '-')
df_unmutated['position'] = df_unmutated.position.str.cat(df_unmutated['direction'].astype(str), sep = ',')
df_unmutated[df_unmutated.duplicated('position', keep = False)].sort_values('position')

# df_unmutated

,chromosome,start,end,unique cells,direction,multiples,singles,position
177187,chr10,100492663,100492664,4,+,0,4,"chr10:100492663-100492664,+"
224114,chr10,100492663,100492664,3,+,0,3,"chr10:100492663-100492664,+"
150436,chr10,10545428,10545429,91,-,19,95,"chr10:10545428-10545429,-"
312634,chr10,10545428,10545429,67,-,17,66,"chr10:10545428-10545429,-"
176507,chr10,108252921,108252922,27,+,1,28,"chr10:108252921-108252922,+"
...,...,...,...,...,...,...,...,...
337640,chrY,90819524,90819525,10,+,0,10,"chrY:90819524-90819525,+"
337641,chrY,90819525,90819526,10,+,0,10,"chrY:90819525-90819526,+"
102838,chrY,90819525,90819526,12,+,1,12,"chrY:90819525-90819526,+"
337642,chrY,90819526,90819527,11,+,0,11,"chrY:90819526-90819527,+"
102839,chrY,90819526,90819527,12,+,1,12,"chrY:90819526-90819527,+"

In [50]:
%%time
df_unmutated = df_unmutated.groupby('position').agg(
            {'unique cells': 'sum', 'multiples': 'first',
             'singles': 'first'}).reset_index()
df_unmutated[df_unmutated['position'] == 'chr10:100492663-100492664,+']
# df_unmutated.duplicated('position', keep = False).sum()
# 390408

CPU times: user 400 ms, sys: 55 Âµs, total: 400 ms
Wall time: 398 ms

                       position  unique cells  multiples  singles
15  chr10:100492663-100492664,+             7          0        4

### Load unmutated df

In [3]:
#### UNMUTATED
# df_unmutated.rename(columns = {'chromosome': 'Chromosome', 'direction': 'strand',
#                                'unique cells':'count of unmutated cell barcodes', 'multiples':'unmutated multi reads', 
#                                'singles': 'unmutated single reads'}, inplace = True)
# df_unmutated['position'] = df_unmutated.Chromosome.str.cat(df_unmutated['start'].astype(str), sep = ':')
# df_unmutated['position'] = df_unmutated.position.str.cat(df_unmutated['end'].astype(str), sep = '-')
# df_unmutated['position'] = df_unmutated.position.str.cat(df_unmutated['strand'].astype(str), sep = ',')
# df_unmutated.sort_values(by = 'position', ascending=True, inplace = True, ignore_index = True)
# # add columns for total umi counts
# df_unmutated['total umi count'] = df_unmutated['unmutated multi reads'] + df_unmutated['unmutated single reads']

# df_filtered_unmutated = df_unmutated.groupby('position')['count of unmutated cell barcodes'].filter( # ,'total umi count'
#     lambda x: (x.sum() >= 5)) # & (x['total umi count'].sum() > 1)

df_unmutated

,position,count of unmutated cell barcodes,unmutated multi reads,unmutated single reads,total umi count
0,"chr10:100070923-100070924,+",1,0,1,1
1,"chr10:100070930-100070931,+",1,1,0,1
2,"chr10:100072600-100072601,+",1,1,0,1
3,"chr10:100072604-100072605,+",1,1,0,1
4,"chr10:100072956-100072957,+",1,0,1,1
...,...,...,...,...,...
207449,"chrY:923027-923028,+",4,3,1,4
207450,"chrY:923037-923038,+",2,2,0,2
207451,"chrY:923041-923042,+",1,1,0,1
207452,"chrY:923042-923043,+",1,1,0,1
207453,"chrY:943703-943704,+",16,16,1,17

## Load agrregated df

In [3]:
df_agg = pd.read_csv('/home/eligol/Documents/01_WIS/01_Rarevar/outputs/statistics_output/PP_htseq_gene/aggregated_intersect.tsv', sep = '\t')
df_agg.rename(columns = {'percent of non ref total reads': 'mutation percent of total umi',
                         'percent of non ref mutated reads': 'mutation percent of umis in mutated cells'}, inplace = True)
df_agg_filtered = df_agg[(df_agg['count of mutated cell barcodes'] + df_agg['count of unmutated cell barcodes']) >= 5]
df_agg

,#Chromosome,start,end,position,mutation percent of total umi,strand,count of unmutated cell barcodes,count of mutated cell barcodes,mutation percent of umis in mutated cells,reference base,R->A multi reads,R->T multi reads,R->G multi reads,R->C multi reads,R->A single reads,R->T single reads,R->G single reads,R->C single reads,mixed reads,unmutated single reads,unmutated multi reads,aggregated cell barcodes,is_snp,is_editing_rep,is_editing_non_rep
0,chr1,3210844,3210845,"chr1:3210844-3210845,-",50.0,-,1,1,100.0,a,0,1,0,0,0,0,0,0,0,0,1,TTTGGTTGTTGGACCC-1,0,0,0
1,chr1,3210846,3210847,"chr1:3210846-3210847,-",50.0,-,1,1,100.0,g,0,0,0,1,0,0,0,0,0,0,1,GGGATGAGTTCCCTTG-1,0,0,0
2,chr1,3210857,3210858,"chr1:3210857-3210858,-",50.0,-,1,1,100.0,t,0,0,0,1,0,0,0,0,0,0,1,TTTGGTTGTTGGACCC-1,0,0,0
3,chr1,3221020,3221021,"chr1:3221020-3221021,-",50.0,-,1,1,100.0,g,1,0,0,0,0,0,0,0,0,0,1,TCCACACTCCTCAATT-1,0,0,0
4,chr1,3221958,3221959,"chr1:3221958-3221959,-",50.0,-,1,1,100.0,g,1,0,0,0,0,0,0,0,0,1,0,AGCCTAATCGCCGTGA-1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369103,chrY,90819780,90819781,"chrY:90819780-90819781,+",100.0,+,0,2,100.0,g,1,0,0,0,1,0,0,0,0,0,0,"TTCCCAGGTCCATCCT-1,CGCCAAGGTATGAAAC-1",0,0,0
369104,chrY,90820000,90820001,"chrY:90820000-90820001,+",100.0,+,0,1,100.0,a,0,0,0,0,0,1,0,0,0,0,0,GGCCGATTCATTATCC-1,0,0,0
369105,chrY,90820001,90820002,"chrY:90820001-90820002,+",100.0,+,0,1,100.0,g,0,0,0,0,0,1,0,0,0,0,0,GGCCGATTCATTATCC-1,0,0,0
369106,chrY,90820004,90820005,"chrY:90820004-90820005,+",100.0,+,0,1,100.0,t,0,0,0,0,1,0,0,0,0,0,0,GGCCGATTCATTATCC-1,0,0,0
369107,chrY,90820005,90820006,"chrY:90820005-90820006,+",50.0,+,1,1,100.0,t,0,0,0,0,0,0,1,0,0,0,1,GGCCGATTCATTATCC-1,0,0,0

In [11]:
ref_g = df_agg[df_agg['reference base'] == 't']
ref_g['mixed reads'].sum()

1597

# make tables after filter snp with snp classsifier

In [8]:
df = pd.read_csv('/home/eligol/Documents/01_WIS/01_Rarevar/outputs/statistics_output/human_RSS9451/df_with_predicted_snp.tsv', sep='\t')

df_overlaps_clf_db = df[(df['is_snp'] == 1) & (df['predicted_as_snp'] == 1)]
df_pred_pos_snp = df[df['predicted_as_snp'] == 1]
df_new_snp = df[(df['is_snp'] != 1) & (df['predicted_as_snp'] == 1)]
df_no_snp = df[(df['is_snp'] != 1) & (df['predicted_as_snp'] != 1)]

df_pred_pos_snp.to_csv('df_pred_pos_snp.tsv', sep='\t',index=False)
df_new_snp.to_csv('df_new_snp_not_known.tsv', sep='\t',index=False)
df_no_snp.to_csv('df_no_snp.tsv', sep='\t',index=False)

In [6]:
df_no_snp

,#Chromosome,start,end,position,percent of non ref total umis,strand,count of unmutated cell barcodes,count of mutated cell barcodes,percent of non ref mutated umis,reference base,R->A multi reads,R->T multi reads,R->G multi reads,R->C multi reads,R->A single reads,R->T single reads,R->G single reads,R->C single reads,mixed reads,total mutation umi count,unmutated single reads,unmutated multi reads,aggregated cell barcodes,total umi counts 1 cells,median percent of non ref umi 1 cells,total umi counts 2 cells,median percent of non ref umi 2 cells,total umi counts 3 cells,median percent of non ref umi 3 cells,total umi counts 4+ cells,median percent of non ref umi 4+ cells,is_snp,is_editing_rep,is_editing_non_rep,predicted_as_snp
3,chr1,632682,632683,"chr1:632682-632683,+",2.39,+,393.0,10,90.91,t,0,0,0,0,4,1,4,2,0,11,373.0,35.0,"GTTCGGGCACCGGAAA-1,TCGCGTTAGTGGTCCC-1,TCTTTCCC...",9.0,100.0,1.0,50.0,0.0,0.0,0.0,0.0,0,0,0,0
4,chr1,632683,632684,"chr1:632683-632684,+",30.33,+,279.0,126,93.43,t,4,0,3,5,35,9,49,32,0,137,263.0,22.0,"ACATCAGTCACCTTAT-1,CATGACAAGGTGATAT-1,ACTGAGTG...",115.0,100.0,11.0,50.0,0.0,0.0,0.0,0.0,0,0,0,0
5,chr1,632684,632685,"chr1:632684-632685,+",14.15,+,346.0,60,92.31,c,1,1,0,0,41,13,4,5,0,65,327.0,32.0,"CTGAAGTGTCGTGGCT-1,GTGCAGCTCGCCTGTT-1,ACATCAGT...",55.0,100.0,5.0,50.0,0.0,0.0,0.0,0.0,0,0,0,0
6,chr1,632685,632686,"chr1:632685-632686,+",12.32,+,354.0,51,91.23,a,0,2,1,0,5,28,9,12,0,57,334.0,31.0,"CTGAAGTGTCGTGGCT-1,TGCGCAGTCTGGCGAC-1,CACAGTAA...",45.0,100.0,6.0,50.0,0.0,0.0,0.0,0.0,0,0,0,0
7,chr1,632686,632687,"chr1:632686-632687,+",8.27,+,371.0,35,94.59,a,0,1,1,1,2,14,14,4,0,37,354.0,32.0,"TACGGTATCCAGAAGG-1,GGACGTCTCATGCAAC-1,CATCGAAC...",33.0,100.0,2.0,50.0,0.0,0.0,0.0,0.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64237,chrY,18990814,18990815,"chrY:18990814-18990815,-",85.00,-,6.0,33,100.00,c,6,0,0,0,28,0,0,0,0,34,2.0,4.0,"AAAGCAACAGACGTAG-1,GGAACTTTCAGCACAT-1,AGAGTGGC...",32.0,100.0,1.0,100.0,0.0,0.0,0.0,0.0,0,0,0,0
64238,chrY,18990832,18990833,"chrY:18990832-18990833,-",76.92,-,6.0,19,100.00,a,0,0,2,0,0,0,18,0,0,20,3.0,3.0,"GGAACTTTCAGCACAT-1,AGAGTGGCACGGTGTC-1,ATCCACCC...",18.0,100.0,1.0,100.0,0.0,0.0,0.0,0.0,0,0,0,0
64239,chrY,19026585,19026586,"chrY:19026585-19026586,-",35.14,-,22.0,13,92.86,a,1,0,3,0,0,0,10,0,0,14,17.0,6.0,"CACCTTGGTGCAACGA-1,AGCATACAGCAGATCG-1,ATGAGGGA...",12.0,100.0,1.0,50.0,0.0,0.0,0.0,0.0,0,0,0,0
64240,chrY,19026586,19026587,"chrY:19026586-19026587,-",26.32,-,26.0,10,90.91,a,1,0,2,0,0,0,8,0,0,11,19.0,8.0,"AGCATACAGCAGATCG-1,GACTAACTCTGTACGA-1,TAGTGGTT...",9.0,100.0,1.0,50.0,0.0,0.0,0.0,0.0,0,0,0,0
64242,chrY,20592907,20592908,"chrY:20592907-20592908,+",14.06,+,110.0,18,100.00,g,3,0,0,0,15,0,0,0,0,18,69.0,41.0,"TGGGAAGGTTGTGGCC-1,TGGGAAGAGGGTCGAT-1,CTTGGCTT...",18.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0

# Information from grouping by )position, CB)

In [43]:
df = pd.read_csv("/home/eligol/Documents/01_WIS/01_Rarevar/outputs/statistics_output/human_SRR9451/merged_mutated_unmutated_no_agg.tsv", sep='\t')

In [45]:
df

,Chromosome,start,end,cell barcode,percent of non ref,strand,reference base,R->A multi reads,R->C multi reads,R->G multi reads,R->T multi reads,R->A single reads,R->C single reads,R->G single reads,R->T single reads,mixed reads,position,total umi count,count of unmutated cell barcodes,unmutated single reads,unmutated multi reads
0,chr8,73290662,73290663,TCGAGGCTCGTACGGC-1,33,-,c,0,0,0,0,0,2,0,1,0,"chr8:73290662-73290663,-",3,4250.0,8179.0,934.0
1,chr8,73290668,73290669,TCGAGGCTCGTACGGC-1,25,-,a,1,0,0,0,2,0,1,0,0,"chr8:73290668-73290669,-",4,4824.0,11154.0,1413.0
2,chr8,73290212,73290213,CTGCGGAGTCCATGAT-1,100,-,c,0,0,0,0,0,0,0,1,0,"chr8:73290212-73290213,-",1,24.0,17.0,7.0
3,chr8,73290650,73290651,CTGCGGAGTCCATGAT-1,50,-,t,0,0,0,0,0,1,0,1,0,"chr8:73290650-73290651,-",2,2458.0,3191.0,298.0
4,chr8,73290334,73290335,GGATTACCAGCGAACA-1,100,-,g,0,0,0,0,1,0,0,0,0,"chr8:73290334-73290335,-",1,88.0,65.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5583920,chr19,18079293,18079294,ACTGAGTTCAGCGACC-1,100,-,c,0,0,0,0,0,0,0,1,0,"chr19:18079293-18079294,-",1,2.0,2.0,0.0
5583921,chr19,18079307,18079308,ACTGAGTTCAGCGACC-1,100,-,a,0,0,0,0,0,0,1,0,0,"chr19:18079307-18079308,-",1,1.0,1.0,0.0
5583922,chr19,18079299,18079300,GAAGCAGGTAGAGCTG-1,100,-,g,0,0,0,0,1,0,0,0,0,"chr19:18079299-18079300,-",1,1.0,1.0,0.0
5583923,chr19,18079300,18079301,GAAGCAGGTAGAGCTG-1,100,-,t,0,0,0,0,0,1,0,0,0,"chr19:18079300-18079301,-",1,1.0,1.0,0.0
5583924,chr19,18079310,18079311,GAAGCAGGTAGAGCTG-1,100,-,a,0,0,0,0,0,0,1,0,0,"chr19:18079310-18079311,-",1,1.0,1.0,0.0

In [54]:
df.groupby(['position','cell barcode']).count()

,,Chromosome,start,end,percent of non ref,strand,reference base,R->A multi reads,R->C multi reads,R->G multi reads,R->T multi reads,R->A single reads,R->C single reads,R->G single reads,R->T single reads,mixed reads,total umi count,count of unmutated cell barcodes,unmutated single reads,unmutated multi reads
position,cell barcode,,,,,,,,,,,,,,,,,,,
"chr10:100068394-100068395,-",ACACCCTAGTTCGCGC-1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"chr10:100068399-100068400,-",ACACCCTAGTTCGCGC-1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"chr10:100068411-100068412,-",ACACCCTAGTTCGCGC-1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"chr10:1000715-1000716,+",CCTTCCCAGAAACGCC-1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"chr10:1000754-1000755,+",CGGTTAAAGCCACCTG-1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"chrY:7379644-7379645,+",GGTGCGTGTGGTACAG-1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"chrY:7381153-7381154,+",CACACCTGTCTGGTCG-1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"chrY:7381249-7381250,+",GATCTAGCAGTTAACC-1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"chrY:7381411-7381412,+",AGTAGTCCAAAGGTGC-1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"chrY:8676140-8676141,+",CTGATAGAGTGTTAGA-1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [52]:
%%time
df_agg = df.groupby(['position','cell barcode']).agg(
        {'Chromosome': 'first', 'start': 'first', 'end': 'first', 'strand': 'first', 'reference base': 'first','R->A multi reads': 'sum', 'R->T multi reads': 'sum', 'R->G multi reads': 'sum',
         'R->C multi reads': 'sum', 'R->A single reads': 'sum', 'R->T single reads': 'sum',
         'R->G single reads': 'sum', 'R->C single reads': 'sum', 'mixed reads': 'sum',
         'count of unmutated cell barcodes': 'first', 'unmutated multi reads': 'first',
             'unmutated single reads': 'first'}).reset_index()

# df_agg.rename(columns={"cell barcode": "aggregated cell barcodes"}, inplace=True)
# df_agg.loc[:, 'count of mutated cell barcodes'] = df_agg.apply(
#     lambda x: len(x['aggregated cell barcodes'].split(',')), axis=1) # add column with count of CB in each position . This can maybe be shorter by using groupby and count

CPU times: user 6.83 s, sys: 1.77 s, total: 8.6 s
Wall time: 8.61 s

In [61]:
df[['position','cell barcode']]#.duplicated(keep=False)

                          position        cell barcode
0         chr8:73290662-73290663,-  TCGAGGCTCGTACGGC-1
1         chr8:73290668-73290669,-  TCGAGGCTCGTACGGC-1
2         chr8:73290212-73290213,-  CTGCGGAGTCCATGAT-1
3         chr8:73290650-73290651,-  CTGCGGAGTCCATGAT-1
4         chr8:73290334-73290335,-  GGATTACCAGCGAACA-1
...                            ...                 ...
5583920  chr19:18079293-18079294,-  ACTGAGTTCAGCGACC-1
5583921  chr19:18079307-18079308,-  ACTGAGTTCAGCGACC-1
5583922  chr19:18079299-18079300,-  GAAGCAGGTAGAGCTG-1
5583923  chr19:18079300-18079301,-  GAAGCAGGTAGAGCTG-1
5583924  chr19:18079310-18079311,-  GAAGCAGGTAGAGCTG-1

[5583925 rows x 2 columns]

In [51]:

filtered_idx = df.groupby(['position','cell barcode']).filter(lambda x: (x['count of mutated cell barcodes'] >= 5) & (df['count of unmutated cell barcodes'] >= 1))
filtered_idx
# df.loc[filtered_idx.index, :]

KeyError: 'count of mutated cell barcodes'

# Compare data after changes of raw stas table columns

In [2]:
df_a = pd.read_csv("/home/eligol/Documents/01_WIS/01_Rarevar/data/outputs/statistics_output/human_RSS9450_after_changes/aggregated_tsv.tsv", sep = '\t')
df_b = pd.read_csv("/home/eligol/Documents/01_WIS/01_Rarevar/data/outputs/statistics_output/human_RSS9450/aggregated_tsv.tsv", sep = '\t')

In [8]:
df_a=df_a.sort_values(by = ['Chromosome','start'])
df_a.head()

,Chromosome,start,end,position,percent of non ref total umis,strand,count of unmutated cell barcodes,count of mutated cell barcodes,percent of non ref mutated umis,reference base,same multi,transition multi,reverse multi,transvertion multi,same single,transition single,reverse single,transvertion single,mixed reads,total mutation umi count,unmutated single reads,unmutated multi reads,aggregated cell barcodes,total umi counts 1 cells,median percent of non ref umi 1 cells,total umi counts 2 cells,median percent of non ref umi 2 cells,total umi counts 3 cells,median percent of non ref umi 3 cells,total umi counts 4+ cells,median percent of non ref umi 4+ cells
0,chr1,14676,14677,"chr1:14676-14677,-",45.45,-,59.0,50,98.04,c,0,9,0,0,1,41,0,0,0,51,56.0,3.0,"TACGGGCTCCTCAACC-1,GAAATGAGTCTAGCGC-1,GTGAAGGC...",49.0,100.0,1.0,50.0,0.0,0.0,0.0,0.0
1,chr1,14701,14702,"chr1:14701-14702,-",0.44,-,216.0,1,100.00,a,0,0,0,0,0,0,0,1,0,1,196.0,28.0,CATATTCGTAGCTCCG-1,1.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
2,chr1,14703,14704,"chr1:14703-14704,-",0.37,-,257.0,1,100.00,g,0,0,0,0,0,1,0,0,0,1,228.0,39.0,GAAATGAGTCTAGCGC-1,1.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
3,chr1,14706,14707,"chr1:14706-14707,-",0.38,-,251.0,1,100.00,t,0,0,0,0,0,0,1,0,0,1,222.0,39.0,TGCCCATTCTGCTGCT-1,1.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
4,chr1,14736,14737,"chr1:14736-14737,-",0.37,-,256.0,1,100.00,c,0,0,0,0,0,1,0,0,0,1,226.0,40.0,AAACCTGCACGGCTAC-1,1.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
df_b=df_b.sort_values(by = ['#Chromosome','start'])

df_b.head()

,#Chromosome,start,end,position,percent of non ref total reads,strand,count of unmutated cell barcodes,count of mutated cell barcodes,percent of non ref mutated reads,reference base,R->A multi reads,R->T multi reads,R->G multi reads,R->C multi reads,R->A single reads,R->T single reads,R->G single reads,R->C single reads,mixed reads,unmutated single reads,unmutated multi reads,aggregated cell barcodes
0,chr1,14676,14677,"chr1:14676-14677,-",45.45,-,59,50,98.04,c,0,9,0,0,0,41,0,1,0,56,3,"TACGGGCTCCTCAACC-1,GAAATGAGTCTAGCGC-1,GTGAAGGC..."
1,chr1,14701,14702,"chr1:14701-14702,-",0.44,-,216,1,100.00,a,0,0,0,0,0,0,0,1,0,196,28,CATATTCGTAGCTCCG-1
2,chr1,14703,14704,"chr1:14703-14704,-",0.37,-,257,1,100.00,g,0,0,0,0,1,0,0,0,0,228,39,GAAATGAGTCTAGCGC-1
3,chr1,14706,14707,"chr1:14706-14707,-",0.38,-,251,1,100.00,t,0,0,0,0,1,0,0,0,0,222,39,TGCCCATTCTGCTGCT-1
4,chr1,14736,14737,"chr1:14736-14737,-",0.37,-,256,1,100.00,c,0,0,0,0,0,1,0,0,0,226,40,AAACCTGCACGGCTAC-1

# Plots

total barcodes x position: 1,000,000
positions with only 1 CB: 500,000
positions with 500 CB: 1,000

// percent of unique positions with n CB (bins) in them
bin1: 500,000 / 501,000(%)
bin500: 1000/501,000(%)

// amount of CB per position
bin1: (500,000 * 1)/ 1,000,000 = 50% 
bin500: (500 * 1000)/ 1,000,000 = 50%

### Heatmaps

In [5]:
df_orig = df
df_filtered = df_filtered
df_unmutated = df_unmutated
df_filtered_unmutated = df_filtered_unmutated

### Merge

In [66]:
# df[df.duplicated('position', keep = False)]

In [123]:
df_agg = df.groupby('position').agg({'R->A multi reads': 'sum',	'R->T multi reads': 'sum',	'R->G multi reads': 'sum',
                                  'R->C multi reads': 'sum','R->A single read': 'sum', 'R->T single read': 'sum',
                                  'R->G single read': 'sum', 'R->C single read': 'sum','mixed reads': 'sum','cell barcode':lambda x: ','.join(x)}).reset_index()

df2 = df.drop_duplicates(subset = 'position')
df_agg = df_agg.merge(df2[['Chromosome', 'start', 'end','strand','reference base','position']], on = 'position')
df_agg.rename(columns={"cell barcode": "aggregated cell barcodes"}, inplace=True)
df_agg.loc[:,'count of mutated cell barcodes'] = df_agg.apply(lambda x: len(x['aggregated cell barcodes'].split(',')), axis = 1)

In [124]:
df_unmutated.columns

Index(['Chromosome', 'start', 'end', 'count of unmutated cell barcodes',
       'strand', 'unmutated multiple reads', 'unmutated single reads',
       'position'],
      dtype='object')

In [125]:
df_unmutated_agg = df_unmutated.groupby('position').agg({'count of unmutated cell barcodes' :'sum', 'unmutated multiple reads':'sum', 'unmutated single reads':'sum'}).reset_index()
df_unmutated_agg[df_unmutated_agg.position == 'chr10:79711710-79711711,+']

,position,count of unmutated cell barcodes,unmutated multiple reads,unmutated single reads
11319,"chr10:79711710-79711711,+",67,7,69

In [ ]:
df_m = df_agg.merge(
    df_unmutated_agg[['position', 'count of unmutated cell barcodes', 'unmutated single reads', 'unmutated multiple reads', ]],
    how='left', on='position')
df_m.fillna(0, inplace=True, downcast='infer')

In [127]:
df_unmutated[df_unmutated.position == 'chr10:111496048-111496049,+']

,Chromosome,start,end,count of unmutated cell barcodes,strand,unmutated multiple reads,unmutated single reads,position
377,chr10,111496048,111496049,53,+,8,58,"chr10:111496048-111496049,+"
378,chr10,111496048,111496049,74,+,11,82,"chr10:111496048-111496049,+"

### count umis

In [128]:
def get_non_ref_percent(line):
    ref_base = line['reference base'].upper()
    line.drop('reference base',inplace=True)
    mutation_cols = line[~line.index.str.startswith(('R->%s' % ref_base ,'unmutated'))].index
    mutation_umi_count = line[mutation_cols].sum()
    umi_col_no_unmutated = line[~line.index.str.startswith(('unmutated'))].index
    umi_count_no_unmutated = line[umi_col_no_unmutated].sum()
    all_umi_count = line.sum()
    percent_of_non_ref_total = round((mutation_umi_count / all_umi_count) * 100,ndigits=2)
    percent_of_non_ref_mutated = round((mutation_umi_count / umi_count_no_unmutated) * 100,ndigits=2)
    return  percent_of_non_ref_mutated, percent_of_non_ref_total

all_umi_cols = [col for col in df_m.columns if col.startswith(('R->','unmutated multiple reads','unmutated single reads'))]
df_m[['percent of non ref mutated', 'percent of non ref total']] = \
    df_m[(['reference base']+all_umi_cols)].parallel_apply(get_non_ref_percent, result_type = 'expand', axis = 1)

#reorder columns
cols = ['Chromosome', 'start', 'end', 'count of unmutated cell barcodes','count of mutated cell barcodes',
       'percent of non ref total', 'percent of non ref mutated', 'strand', 'reference base', 'R->A multi reads',
       'R->T multi reads', 'R->G multi reads', 'R->C multi reads',
       'R->A single read', 'R->T single read', 'R->G single read',
       'R->C single read', 'mixed reads', 'unmutated single reads', 'unmutated multiple reads', 'position',
       'aggregated cell barcodes']
df_m = df_m[cols]
#sort df by chromosome and position
df_m.sort_values(by=['Chromosome', 'start'], inplace = True)

### Get regions of positions where 'percent of non ref' is below 75 in average

In [173]:
df_agg.rolling(5,center=True, min_periods=1).mean()#[col] <= percent_to_filter]
df_agg

,Chromosome,start,end,unmutated unique cell barcodes,count of cell barcodes,percent of non ref total,percent of non ref mutated,strand,reference base,R->A multi reads,R->T multi reads,R->G multi reads,R->C multi reads,R->A single read,R->T single read,R->G single read,R->C single read,mixed reads,unmutated singles,unmutated multiples,position,aggregated cell barcodes
189388,chr1,3043203,3043204,NaN,1,100,100,-,t,0,0,0,0,1,0,0,0,0,NaN,NaN,"chr1:3043203-3043204,-",CTGTTTACACACCGAC-1
189416,chr1,3082526,3082527,NaN,1,100,100,+,g,0,0,0,0,1,0,0,0,0,NaN,NaN,"chr1:3082526-3082527,+",CTCGAGGCACACTGCG-1
189417,chr1,3082533,3082534,NaN,1,100,100,+,c,0,0,0,0,1,0,0,0,0,NaN,NaN,"chr1:3082533-3082534,+",CTCGAGGCACACTGCG-1
190396,chr1,3630794,3630795,NaN,2,100,100,-,a,0,0,0,0,0,0,0,2,0,NaN,NaN,"chr1:3630794-3630795,-","ATTTCTGAGCCTCGTG-1,CGTGTCTAGTTCGCGC-1"
190397,chr1,3630805,3630806,NaN,1,100,100,-,a,0,0,0,0,0,0,1,0,0,NaN,NaN,"chr1:3630805-3630806,-",CGTGTCTAGTTCGCGC-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421288,chrY,90828669,90828670,NaN,2,100,100,-,t,0,0,0,0,0,0,0,2,0,NaN,NaN,"chrY:90828669-90828670,-","CAAGGCCCAAATTGCC-1,GGGAATGTCGGCGCTA-1"
421289,chrY,90828670,90828671,NaN,2,100,100,-,c,0,0,0,0,0,2,0,0,0,NaN,NaN,"chrY:90828670-90828671,-","GGGAATGTCGGCGCTA-1,CAAGGCCCAAATTGCC-1"
421290,chrY,90828674,90828675,NaN,1,100,100,-,t,0,0,0,0,0,0,0,1,0,NaN,NaN,"chrY:90828674-90828675,-",GGGAATGTCGGCGCTA-1
421291,chrY,90828717,90828718,NaN,2,100,100,+,t,0,0,0,0,0,0,2,0,0,NaN,NaN,"chrY:90828717-90828718,+","CGGACACAGATGCCTT-1,CTCGTACCAGTGACAG-1"
421292,chrY,90828717,90828718,NaN,1,100,100,-,a,0,0,0,0,0,0,0,1,0,NaN,NaN,"chrY:90828717-90828718,-",GGAGCAAAGATCCTGT-1

In [238]:
from itertools import groupby, cycle 

percent_to_filter = 75
col = 'percent of non ref mutated'

def groupSequence(l): 
    temp_list = iter(l)
    next(temp_list)
    groups = groupby(l, key = lambda j: j + 10 >= next(temp_list)) 

    for k, v in groups: 
        if k: 
            yield tuple(v) + (next((next(groups)[1])), )

end_position = df_agg[df_agg.rolling(10, min_periods=1).mean()[col] <= percent_to_filter]['end']
tpls = list(groupSequence(end_position))
print(*tpls[:10], sep='\n')

(4776574, 4776575, 4776576, 4776579, 4776584, 4776590)
(4776603, 4776605, 4776606)
(4776620, 4776623, 4776626, 4776633, 4776638, 4776646, 4776650, 4776653, 4776656, 4776663)
(4776679, 4776681)
(9942336, 9942343, 9942344, 9942346, 9942347, 9942351, 9942352, 9942357, 9942358, 9942359, 9942362, 9942363, 9942364, 9942371, 9942376, 9942379, 9942383, 9942387)
(9942610, 9942611, 9942614, 9942619, 9942621, 9942622, 9942623, 9942625, 9942626, 9942627, 9942631, 9942632, 9942633, 9942634, 9942635, 9942638, 9942640, 9942642, 9942643, 9942645, 9942646, 9942649, 9942651, 9942652, 9942657, 9942658, 9942659, 9942660, 9942661, 9942662, 9942663, 9942664, 9942666, 9942668, 9942671, 9942673, 9942674, 9942676, 9942681, 9942683, 9942684, 9942686, 9942689, 9942690, 9942697, 9942702, 9942703)
(10025010, 10025013, 10025016)
(10025056, 10025062)
(10027123, 10027128, 10027129, 10027134, 10027136, 10027145, 10027155, 10027156, 10027162)
(13564935, 13564936, 13564937, 13564939, 13564942, 13564949, 13564951, 13564955, 13564957, 13564958, 13564959, 13564963, 13564969, 13564970, 13564975, 13564977, 13564980, 13564981, 13564982, 13564983, 13564990, 13564994, 13565000, 13565001, 13565003, 13565005)

Int64Index([190679, 190680], dtype='int64')

In [237]:
tpl = tpls[1]
idx = df_agg[df_agg['end'].isin(list(tpl))].index
print(tpl)
df_agg.loc[(idx.min() - 10): (idx.max()+10),:]

(4776603, 4776605, 4776606)

,Chromosome,start,end,unmutated unique cell barcodes,count of cell barcodes,percent of non ref total,percent of non ref mutated,strand,reference base,R->A multi reads,R->T multi reads,R->G multi reads,R->C multi reads,R->A single read,R->T single read,R->G single read,R->C single read,mixed reads,unmutated singles,unmutated multiples,position,aggregated cell barcodes
192630,chr1,4776559,4776560,117.0,1,99,33,-,t,0,1,0,0,0,1,0,1,0,144.0,20.0,"chr1:4776559-4776560,-",GGCTGGTGTACCCAAT-1
192631,chr1,4776564,4776565,188.0,1,100,100,-,c,0,0,0,0,0,0,1,0,0,218.0,47.0,"chr1:4776564-4776565,-",AGCAGCCTCCCATTTA-1
192632,chr1,4776567,4776568,173.0,1,100,100,-,a,0,0,0,0,0,1,0,0,0,197.0,37.0,"chr1:4776567-4776568,-",CCCAGTTCATGTAAGA-1
192633,chr1,4776572,4776573,269.0,3,99,60,-,a,1,0,0,0,1,2,1,0,0,308.0,53.0,"chr1:4776572-4776573,-","CGTTCTGCACTTACGA-1,CAGAGAGAGTACCGGA-1,GATCTAGC..."
192634,chr1,4776573,4776574,316.0,4,99,40,-,g,0,0,2,0,0,0,4,4,0,383.0,74.0,"chr1:4776573-4776574,-","GATCTAGCAGTGACAG-1,AACTTTCGTCGCGTGT-1,GTATTCTG..."
192635,chr1,4776574,4776575,320.0,3,99,33,-,g,0,0,2,0,0,0,4,3,0,385.0,74.0,"chr1:4776574-4776575,-","GATCTAGCAGTGACAG-1,CAGAGAGAGTACCGGA-1,GTATTCTG..."
192636,chr1,4776575,4776576,310.0,3,99,33,-,a,2,0,0,0,4,3,0,0,0,361.0,73.0,"chr1:4776575-4776576,-","GATCTAGCAGTGACAG-1,GTATTCTGTTGGTTTG-1,CAGAGAGA..."
192637,chr1,4776578,4776579,138.0,1,100,100,-,g,0,0,0,0,0,1,0,0,0,175.0,32.0,"chr1:4776578-4776579,-",CAGCTGGGTCTCTTTA-1
192638,chr1,4776583,4776584,155.0,1,100,50,-,c,0,0,0,0,0,1,0,1,0,190.0,40.0,"chr1:4776583-4776584,-",CACATAGAGATAGTCA-1
192639,chr1,4776589,4776590,193.0,1,99,33,-,g,0,0,0,0,1,0,2,0,0,227.0,53.0,"chr1:4776589-4776590,-",CAGCATATCCAGATCA-1
192640,chr1,4776602,4776603,170.0,1,100,50,-,a,0,0,0,0,1,0,0,1,0,209.0,38.0,"chr1:4776602-4776603,-",TTGGCAACACGCTTTC-1
192641,chr1,4776604,4776605,188.0,1,100,50,-,t,0,0,0,0,0,1,0,1,0,230.0,63.0,"chr1:4776604-4776605,-",ATCTACTGTGATAAAC-1
192642,chr1,4776605,4776606,174.0,1,100,50,-,a,1,0,0,0,0,0,0,1,0,206.0,53.0,"chr1:4776605-4776606,-",CCTACACGTGGCGAAT-1
192643,chr1,4776619,4776620,151.0,1,100,100,-,t,0,0,0,0,0,0,0,1,0,191.0,48.0,"chr1:4776619-4776620,-",GGAACTTGTCACTTCC-1
192644,chr1,4776622,4776623,146.0,1,99,33,-,t,0,1,0,0,0,1,0,1,0,196.0,43.0,"chr1:4776622-4776623,-",GCACTCTGTTCCGGCA-1
192645,chr1,4776625,4776626,151.0,1,99,33,-,c,0,0,0,0,0,0,1,2,0,199.0,45.0,"chr1:4776625-4776626,-",CTCGTCATCATGTAGC-1
192646,chr1,4776632,4776633,142.0,1,99,33,-,g,0,0,0,0,1,0,2,0,0,186.0,36.0,"chr1:4776632-4776633,-",CAGCTGGGTCTCTTTA-1
192647,chr1,4776637,4776638,171.0,1,100,50,-,g,0,0,0,0,0,1,1,0,0,198.0,43.0,"chr1:4776637-4776638,-",TTCGAAGTCTACGAGT-1
192648,chr1,4776645,4776646,127.0,1,99,50,-,g,0,0,0,0,0,1,1,0,0,136.0,25.0,"chr1:4776645-4776646,-",TCTATTGCAAAGTCAA-1
192649,chr1,4776649,4776650,253.0,2,99,50,-,a,0,0,0,0,2,1,1,0,0,302.0,41.0,"chr1:4776649-4776650,-","GGAACTTCAAGCTGGA-1,CGTGTCTAGTTCGCGC-1"
192650,chr1,4776652,4776653,153.0,1,100,100,-,t,0,0,0,0,0,0,0,1,0,165.0,35.0,"chr1:4776652-4776653,-",TTGCGTCAGTGTCCCG-1
192651,chr1,4776655,4776656,120.0,1,100,100,-,a,0,0,0,0,0,0,0,1,0,148.0,25.0,"chr1:4776655-4776656,-",GTTAAGCCAATGGATA-1
192652,chr1,4776662,4776663,128.0,1,99,50,-,a,0,0,0,0,1,0,0,1,0,145.0,16.0,"chr1:4776662-4776663,-",GACGTTACAGCTCCGA-1